### PR TITLE
Display a friendlier name for "Open With" menus in Windows

### PR DESCRIPTION
**Pull request by jaimergp**
### Description

Hoping this fixes the issue reported at https://github.com/conda/menuinst/issues/185#issuecomment-2197286218

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by jaimergp** [comment]
pre-commit.ci autofix

**Comment by mrclary** [comment]
I'll give this a try locally.

**Comment by mrclary** [comment]
It did not appear to affect anything. I can see that the registry entry is different
Screenshot 2024-07-01 at 12 28 04 PM

but the associated application is still "Python", and "Spyder (spy6b3d10)" does not appear in any application list to choose from.

Screenshot 2024-07-01 at 12 29 18 PM

**Comment by jaimergp** [comment]
Oh, I do see it in the "Details column" there in the background, next to the file size. Maybe that's what they meant with `FriendlyTypeName`?

**Comment by jaimergp** [comment]
I found what [VS Code uses for PY files](https://github.com/microsoft/vscode/blob/3ad2eb18b5a8ffba3f2d09b9abfe0a819cf2e99f/build/win32/code.iss#L998-L1004) so I'm going to give it a try now with a couple commits. I don't have a Windows VM around right now so it's going to be a blind guess. I appreciate the patience here, thanks!

**Comment by jaimergp** [comment]
I think that's the best we can do for now... :/ The "Open With" icon is going to default to the EXE icon, no matter what. I'll mark this as ready so we can start the review.

**Review by marcoesters — COMMENTED** [review]
LGTM overall, just needs type consistency

**Review by marcoesters — APPROVED** [review]

**Pull request merged**
