### PR TITLE
Changelog for 1.4.18 release

### PR DESCRIPTION
**Pull request by chenghlee**

### CODE REVIEW

**Review by LtDan33 — APPROVED** [review]
Looks good!

**Comment by chenghlee** [comment]
FYI @ericpre @isuruf: we've tagged a new release. Please let us know if there are open PRs in constructor that need to get merged, and we can work on releasing that as well.

**Comment by isuruf** [comment]
Thanks @chenghlee. There's a couple of PRs in contructor that needs attention,
https://github.com/conda/constructor/pull/458
https://github.com/conda/constructor/pull/449

**Comment by ericpre** [comment]
> Thanks @chenghlee. There's a couple of PRs in contructor that needs attention,
> [conda/constructor#458](https://github.com/conda/constructor/pull/458)
> [conda/constructor#449](https://github.com/conda/constructor/pull/449)

Thanks @chenghlee, yes, a `constructor` release would be good to remove the corresponding patches in `conda-standalone`. conda/constructor#458/conda/constructor#459 (similar fix) is an easy bug fix.

**Pull request merged**
