### PR TITLE
Rewrite for cross-platform compatibility (following conda/ceps#8)

### PR DESCRIPTION
**Pull request by jaimergp**
CEP: https://github.com/conda/ceps/pull/8

# To do

- [X] Create new project scaffold and move old code to `_legacy`
- [X] Create JSON-Schema for the input files
- [X] Implement shortcut creation for Windows
- [X] Implement shortcut creation for Linux
- [X] Implement shortcut creation for MacOS
- [X] Implement environment activation on Unix
- [X] Implement environment activation on Windows
- [x] Cleanup tasks: `conda [env] remove` should also delete created menu items
- [X] Do not depend on `pydantic` at runtime
- [X] Implement superuser elevation on Windows
- [x] Implement superuser elevation on Linux (?)
- [x] Implement superuser elevation on MacOS (?)
- [ ] Test elevation
- [x] Handle interference of PYTHON* variables with shortcuts
- [x] macOS integrations: entitlements and permissions
- [x] macOS integrations: keyboard shortcuts registration
- [X] Clean up unused code
- [X] Sort common Windows utilities

### CODE REVIEW

**Comment by jaimergp** [comment]
Ok, basic tests are passing yay! 🥳 

I am not testing the output of Windows yet, but the LNK file is indeed created _without_ a C extension.

**Comment by jaimergp** [comment]
c78a6f7 introduces full environment activation in all platforms. I am not sure if the `conda_exe ` location code will be enough for all situations (conda in base prefix, conda in target prefix, conda-standalone, micromamba), but we'll work on that as we try it.

**Comment by jaimergp** [comment]
`conda` has a bug where `conda env remove` won't run the unlink actions, so it won't remove the menu artifacts. `conda remove --all` does. This has been submitted as an issue [here](https://github.com/conda/conda/issues/11092).

Other than that, I think we can call this the first alpha!

**Comment by jaimergp** [comment]
I'll study the changes suggested by #103 to get rid of pywin32 here too.

**Comment by jezdez** [comment]
@jaimergp As a matter of principle, we should vote on the CEP before we merge large changes like this, maybe even reviewing them!

**Comment by jaimergp** [comment]
Yes, sorry, that review request was sent automatically by the GH configuration after updating the branch 🤷

**Comment by jezdez** [comment]
@jaimergp D'oh! TIL :D

**Comment by hoechenberger** [comment]
Wow. All but one checkboxes of the todo are ticked ✅ Does this mean this work is almost done? 😲😎

**Comment by jaimergp** [comment]
Not yet, I am debugging some elevation stuff I am not happy with, and we also got a report where PYTHON* variables disrupt the launch of the program.

But it's getting closer :)

**Comment by jaimergp** [comment]
@conda/constructor - how do you feel about merging this to a feature branch to keep further iterations well isolated?

**Comment by jezdez** [comment]
@jaimergp +1 

For sanity reasons, I would also suggest polishing the CEP and get it voted on ASAP.

**Comment by jaimergp** [comment]
Updated the target branch and merging.

**Pull request merged**
